from . import res_company
from . import res_partner
from . import hr_employee
from . import product_template
from . import account_move
from . import commission_rule
from . import booking
from . import booking_line
from . import expense
from . import payout
from . import dashboard
